"""unique playbook rule_key per playbook

Revision ID: 76632dab1ed8
Revises: 7fcbc30669ee
Create Date: 2026-07-13 17:02:26.641736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76632dab1ed8'
down_revision: Union[str, None] = '7fcbc30669ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_playbook_rule_key', 'playbook_rule', ['playbook_id', 'rule_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_playbook_rule_key', 'playbook_rule', type_='unique')
    # ### end Alembic commands ###
