"""esign envelope tracking on request

Revision ID: 7fcbc30669ee
Revises: 749f2185531e
Create Date: 2026-07-13 16:17:56.902801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fcbc30669ee'
down_revision: Union[str, None] = '749f2185531e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('esign_envelope_id', sa.String(), nullable=True))
    op.add_column('request', sa.Column('esign_provider', sa.String(), nullable=True))
    op.add_column('request', sa.Column('esign_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'esign_status')
    op.drop_column('request', 'esign_provider')
    op.drop_column('request', 'esign_envelope_id')
    # ### end Alembic commands ###
